export enum EnvConfigEnum {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  TOKEN_SECRET = 'TOKEN_SECRET',
  REFRESH_TOKEN_SECRET = 'REFRESH_TOKEN_SECRET',
  CONNECTION_STRING = 'CONNECTION_STRING',
  TOKEN_EXPIRATION_TIME = 'TOKEN_EXPIRATION_TIME',
  REFRESH_TOKEN_EXPIRATION_TIME = 'REFRESH_TOKEN_EXPIRATION_TIME',
}
